### PR TITLE
Fix custom accessibility actions for buttons 

### PR DESCRIPTION
**Pull request by ewdavison**
Fix custom accessibility actions for buttons by passing the actions and handler when creating the view.

### CODE REVIEW

**Comment by berickson1** [comment]
Build fails

```
$ npm run build

> reactxp@0.42.0-rc.25 build /src/reactxp
> npm run tslint && tsc

> reactxp@0.42.0-rc.25 tslint /src/reactxp
> tslint --project tsconfig.json -r tslint.json -r ./node_modules/tslint-microsoft-contrib --fix || true

src/native-common/Button.tsx(103,17): error TS2339: Property 'accessibilityActions' does not exist on type 'ViewProps'.
```

**Comment by erictraut** [comment]
@ewdavison && @berickson1, what's the status of this PR?

**Comment by erictraut** [comment]
@wedavidson & @berickson1, what's the status of this PR? Should I just close it?

**Comment by berickson1** [comment]
Last I tried to build it, it failed. @ewdavison ?

**Comment by erictraut** [comment]
No response on this one for more than a month, so I'm closing it.

**Pull request closed without merging**
