### PR TITLE
Convert the web Alert from notification to Modal

### PR DESCRIPTION
**Pull request by psegalen**
First attempt to convert current web specific Alert component from a web notification to a Modal.
Related to issue #169

### CODE REVIEW

**Comment by erictraut** [comment]
@psegalen - thanks for the submission. Sorry for the slow response. I've been on vacation for the past two weeks. I just pushed an updated PR to your branch. Please review and let me know if it looks good. If so, I can merge it into master.

**Comment by psegalen** [comment]
@erictraut - no problem about the delay, we all need vacation from time to time!
Your update seems good to me, it shows me how much my code needed to be cleaned... If I submit another PR someday, I'll try to remember this.

**Comment by MovingGifts** [comment]
Hmmm, I don't see the RX.Modal working, it still prompts the notification way (no change), I think something with the version? I have this atm:
```json
"reactxp": "^0.42.1",
```
installed with:

`npm i -S reactxp`

Wondering how I can install the latest reactxp package that contains it?

**Comment by erictraut** [comment]
I assume you mean RX.Alert. The updated behavior is available only in the master branch, not the 0.42.x branch. You can use version "0.46.0_rc.1".

**Comment by MovingGifts** [comment]
Yup, sorry I meant the RX.Alert's modal :)

I tried this to install the version "0.46.0_rc.1":
```
npm i -S reactxp@0.46.0_rc.1
```
Then I got an error like so:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for reactxp@0.46.0_rc.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
Not sure why I got that error, am I installing it incorrectly?

**Comment by MovingGifts** [comment]
I tried it with a dash instead like so: `0.46.0-rc.1`

Which installed but I still don't see the `src/AlertModalContent.tsx`

**Comment by MovingGifts** [comment]
The following seemed to work for the time being, but once `0.46` is out, I will change it to that.
```
"reactxp": "git+https://github.com/Microsoft/reactxp.git"
```

**Comment by MovingGifts** [comment]
Sorry to keep posting, but I get an error in web (only checked in web) with:

`"reactxp": "git+https://github.com/Microsoft/reactxp.git"`

screen shot 2017-09-08 at 7 04 01 pm
The error is because there isn't a `dist` folder at all with this version and `node_modules/reactxp/index.js` has this line:
```js
// Export web by default. Other platforms have custom index.[platform].js files
module.exports = require('./dist/web/ReactXP.js');
```
The `0.46.0-rc.1` version on npm install creates the `dist` directory correctly at `node_modules/reactxp/dist` so there is no error and it loads the web app, but the web alert is not available in that version.

Not sure what to do :(

**Comment by erictraut** [comment]
If you are using a published version of reactxp, the dist directly will be populated already. If you're directly checking out the reactxp code from git, you'll need to build reactxp yourself. Use "npm install" and "npm run build" to populate the dist directory.

**Comment by MovingGifts** [comment]
Yup, that did it :) Thank you so much!

**Pull request merged**
