### PR TITLE
Update TodoList sample to modern react-native + deps + eslint + docs

### PR DESCRIPTION
**Pull request by mikehardy**
Hi there!

I think the TodoList sample is the flagship of the project personally

This is the full demo of native + web with bootstrapping and shimming etc handled nicely out of the box 

But the developer experience with it right now is a bit stale, starting people off with react-native 0.59, stale deps, lots of console errors etc. Out-of-the-box developers are faced with an rn59->rn60 transition (ouch!) and the tslint->eslint transition (which wasn't that much fun either to be honest)

That's no fun, as noticed in #1212

Also the docs don't help people with pod install, they don't handle native app start, and the web docs were split, so I cleaned those up

All works for me in testing web, android and ios on macOS and linux build hosts. 

So @deregtd as I hinted at in #1213 here's an update split into atomic commits so it's a bit easier to review, though upgrades are never the easiest

Each commit has a comment explaining itself.

Notes:
- Should work for Windows as a development environment? 
- May work for react-native-windows (I'm not sure but the dep went from 0.59 to 0.62...)
- I left a bunch of eslint errors because I did not want to make policy, this PR is intended to be opinion neutral / no controversy

### CODE REVIEW

**Comment by fbartho** [comment]
I’m super interested in this.

We’re about to greatly expand our use of reactxp and our previous use didn’t actually include active web usage.

Having an updated, working, web starter would be great!

**Comment by mikehardy** [comment]
@fbartho feel free to pull my branch and start from there. It's based on what I learned was necessary over the year upgrading my work project so it's in production use, then applied as mechanically and with as light a touch as I could manage here. If someone else were to test it and verify I didn't do anything ridiculous that would probably help it get merged here

**Comment by mikehardy** [comment]
I posted a related PR in the navigation library that will squash the last remaining warnings received in the out-of-the-box experience, cross-link https://github.com/microsoft/react-native-experimental-navigation/pull/6

**Comment by mikehardy** [comment]
Let me know if there's anything I can do to help review that isn't mentioned in the individual commits, happy to explain or polish bits if needed

**Comment by mikehardy** [comment]
@deregt the related react-native-experimental-navigation change went in, I think we're just a commit here away from having the flagship TodoList sample be warning-free / error-free out of the box for any new adopters, which would (one hopes...) imply more folks providing free maintenance going forward as well :-)

Might even get someone motivated to wrap / expose the new Pressable element from react-native with more folks having good DX on first use and adopting

**Comment by mikehardy** [comment]
@deregtd  the related react-native-experimental-navigation change went in, I think we're just a commit here away from having the flagship TodoList sample be warning-free / error-free out of the box for any new adopters, which would (one hopes...) imply more folks providing free maintenance going forward as well :-)

Might even get someone motivated to wrap / expose the new Pressable element from react-native with more folks having good DX on first use and adopting

**Comment by fbartho** [comment]
@mikehardy! -- This is the first I hear about the [Pressable](https://reactnative.dev/docs/pressable) element -- this is super timely as we're starting to extract / build our design system for multiple-app use.

Damn; now I need to read up on it, and figure out if we should base our root touchable items on that element instead of on `RX.Button`

**Comment by erictraut** [comment]
@mikehardy, thanks for doing this! There's a small merge conflict. If you resolve that, I'll merge these changes.

**Comment by mikehardy** [comment]
@erictraut - sure thing! the conflict was all in `package-lock.json` which is derived data, so what I did was `git pull upstream master` on my branch (which exposed the conflict) then deleted package-lock.json and ran `npm i` again to regenerate it, then I force-pushed to my branch so it's clean commits and up to date

The result should be up to date with the dependabot merges and my changes

**Comment by erictraut** [comment]
Thanks @mikehardy! Just merged.

**Review by JasonMiller4 — COMMENTED** [review]
``

**Pull request merged**
