### PR TITLE
Replace all string refs with React.RefObject

### PR DESCRIPTION
**Pull request by berickson1**
String refs are deprecated and should not be used

### CODE REVIEW

**Comment by berickson1** [comment]
Please hold merging for more extensive testing - posting for initial review to ensure I didn't miss anything

**Comment by erictraut** [comment]
FWIW, it looks good to me.

**Comment by berickson1** [comment]
Had to bump the min version of reactxp for compatibility with the optional generic argument. Also bumped to 2.0.0 for release (from rc). I think we're good to move VLV from rc state to release

**Comment by erictraut** [comment]
@berickson1, I published reactxp-virtuallistview 2.0.0

**Pull request merged**
